import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1760924983971 implements MigrationInterface {
    name = 'Init1760924983971'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" DROP CONSTRAINT "FK_PhoneNumber_User"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_User_Role"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "FK_TopUp_Wallet"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "FK_Wallet_User"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "FK_PriceHistory_Company"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "FK_Company_Market"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "FK_Transaction_User"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "FK_Transaction_Company"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "FK_TP_User"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "FK_TP_Company"`);
        await queryRunner.query(`ALTER TABLE "auditoria" DROP CONSTRAINT "FK_Auditoria_User"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "CK__recarga__monto__725BF7F6"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "CK__wallet__categori__6E8B6712"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "CK__precio_hi__preci__68D28DBC"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CK__empresa__accione__6319B466"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CK__empresa__accione__640DD89F"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CK__empresa__estado__6501FCD8"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "CK__transaccio__tipo__7AF13DF7"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "CK__transacci__preci__7BE56230"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "CK__cartera_t__canti__7720AD13"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "CK__cartera_t__costo__7814D14C"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "UQ_Company_PriceTimestamp"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "UQ_User_Company"`);
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" DROP CONSTRAINT "DF_fda56775b3e828a758b3d3f7867"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "DF_762fedc5a858bbb008722708ccd"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "UQ__usuarios__8C585C047AD715A0"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "UQ__usuarios__AB6E6164F0770675"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "DF_37c5fbfba67129199a97366cce3"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD "fecha_hora" datetime2 NOT NULL CONSTRAINT "DF_37c5fbfba67129199a97366cce3" DEFAULT getdate()`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "DF_435d6261bd80a552fcc72cbd7ca"`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "DF_435d6261bd80a552fcc72cbd7ca" DEFAULT 0 FOR "saldo"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "DF_47f5efefb36304070dad826490f"`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "DF_47f5efefb36304070dad826490f" DEFAULT 0 FOR "consumo_diario"`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP CONSTRAINT "UQ__mercado__72AFBCC6427EF4C9"`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "nombre" varchar(35) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD CONSTRAINT "UQ_cd029c805ebe7a9085206c25ac2" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "estado" varchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "moneda"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "moneda" varchar(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "DF_a7551282e0c348adaf1f1421d82"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD "fecha_hora" datetime2 NOT NULL CONSTRAINT "DF_a7551282e0c348adaf1f1421d82" DEFAULT getdate()`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "UQ__empresa__72AFBCC62BAAA1AC"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "nombre" varchar(35) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "UQ_fb0e2384af944c2fb6ac781c625" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "estado" varchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "justificacion_delistar"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "justificacion_delistar" varchar(35)`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "DF_1aee4d714a36878b604b2abc75f"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD "fecha_hora" datetime2 NOT NULL CONSTRAINT "DF_1aee4d714a36878b604b2abc75f" DEFAULT getdate()`);
        await queryRunner.query(`ALTER TABLE "auditoria" DROP CONSTRAINT "DF_9c9ae9e15c3caf7d555c6b9f354"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_86c1ab44c24b70ce469068f9c6" ON "usuarios" ("alias") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_446adfc18b35418aac32ae0b7b" ON "usuarios" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "REL_1079a248779c565ecfb24dfcf9" ON "wallet" ("id_user") WHERE "id_user" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b563b1d3517cd00923ac53658c" ON "precio_historico" ("id_empresa", "fecha_hora") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fd2e9b3fb743bdd44e23d6cfd9" ON "cartera_trader" ("id_user", "id_empresa") `);
        await queryRunner.query(`ALTER TABLE "recarga" ADD CONSTRAINT "CHK_311dd7a62f5ad78a856812709c" CHECK ("monto" > 0)`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "CHK_94c0b622a5bec95341b60e4716" CHECK ("categoria" IN ('Junior', 'Mid', 'Senior'))`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "CHK_5d34dd3d8bf9a73f79e4e17637" CHECK ("precio" >= 0)`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CHK_40dcf5529a8a5acaa5282f079c" CHECK ("capital_actual" >= 0)`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CHK_de597f03322b20ff7c23cf81c4" CHECK ("estado" IN ('Listado', 'No Listado'))`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CHK_1cd1d640e95b1e551260aeec85" CHECK ("acciones_disponibles" >= 0)`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CHK_b2012343abf67454f6351a8f53" CHECK ("acciones_totales" >= 0)`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "CHK_761d46d733c48f16012a32fa1c" CHECK ("precio" >= 0)`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "CHK_8565e99c9c6675d1bf5beff093" CHECK ("tipo" IN ('Buy', 'Sell'))`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "CHK_c6b143229e41d9e1f691319715" CHECK ("costo_promedio" >= 0)`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "CHK_e326eb489f5d2f2f286cc57410" CHECK ("cantidad_acciones" >= 0)`);
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" ADD CONSTRAINT "FK_86cf8f81322568fd0fd3cb4f830" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_c3b96775833e656856573e19334" FOREIGN KEY ("id_role") REFERENCES "roles"("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD CONSTRAINT "FK_595fbbcc1fab4ea343b73f21c22" FOREIGN KEY ("id_wallet") REFERENCES "wallet"("id_wallet") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "FK_1079a248779c565ecfb24dfcf92" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "FK_2c528e409b7c24671214c65f6a0" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "FK_059e05ba5dd66c119eb44de19cb" FOREIGN KEY ("id_mercado") REFERENCES "mercado"("id_mercado") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "FK_84511f3f65763d8bd1785ca1872" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "FK_70bb0ba967bb7f2d506f28cbf93" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "FK_f50d9b26744c461d9d4bf16dcbd" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "FK_c6d3c2972ceda78bf77a8af905b" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auditoria" ADD CONSTRAINT "FK_2a391b3092635e1a7ef4344a566" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auditoria" DROP CONSTRAINT "FK_2a391b3092635e1a7ef4344a566"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "FK_c6d3c2972ceda78bf77a8af905b"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "FK_f50d9b26744c461d9d4bf16dcbd"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "FK_70bb0ba967bb7f2d506f28cbf93"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "FK_84511f3f65763d8bd1785ca1872"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "FK_059e05ba5dd66c119eb44de19cb"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "FK_2c528e409b7c24671214c65f6a0"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "FK_1079a248779c565ecfb24dfcf92"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "FK_595fbbcc1fab4ea343b73f21c22"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_c3b96775833e656856573e19334"`);
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" DROP CONSTRAINT "FK_86cf8f81322568fd0fd3cb4f830"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "CHK_e326eb489f5d2f2f286cc57410"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" DROP CONSTRAINT "CHK_c6b143229e41d9e1f691319715"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "CHK_8565e99c9c6675d1bf5beff093"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "CHK_761d46d733c48f16012a32fa1c"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CHK_b2012343abf67454f6351a8f53"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CHK_1cd1d640e95b1e551260aeec85"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CHK_de597f03322b20ff7c23cf81c4"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "CHK_40dcf5529a8a5acaa5282f079c"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "CHK_5d34dd3d8bf9a73f79e4e17637"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "CHK_94c0b622a5bec95341b60e4716"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "CHK_311dd7a62f5ad78a856812709c"`);
        await queryRunner.query(`DROP INDEX "IDX_fd2e9b3fb743bdd44e23d6cfd9" ON "cartera_trader"`);
        await queryRunner.query(`DROP INDEX "IDX_b563b1d3517cd00923ac53658c" ON "precio_historico"`);
        await queryRunner.query(`DROP INDEX "REL_1079a248779c565ecfb24dfcf9" ON "wallet"`);
        await queryRunner.query(`DROP INDEX "IDX_446adfc18b35418aac32ae0b7b" ON "usuarios"`);
        await queryRunner.query(`DROP INDEX "IDX_86c1ab44c24b70ce469068f9c6" ON "usuarios"`);
        await queryRunner.query(`ALTER TABLE "auditoria" ADD CONSTRAINT "DF_9c9ae9e15c3caf7d555c6b9f354" DEFAULT newid() FOR "id_auditoria"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP CONSTRAINT "DF_1aee4d714a36878b604b2abc75f"`);
        await queryRunner.query(`ALTER TABLE "transaccion" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD "fecha_hora" datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "DF_1aee4d714a36878b604b2abc75f" DEFAULT getdate() FOR "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "justificacion_delistar"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "justificacion_delistar" nvarchar(35)`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "estado" nvarchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP CONSTRAINT "UQ_fb0e2384af944c2fb6ac781c625"`);
        await queryRunner.query(`ALTER TABLE "empresa" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD "nombre" nvarchar(35) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "UQ__empresa__72AFBCC62BAAA1AC" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP CONSTRAINT "DF_a7551282e0c348adaf1f1421d82"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD "fecha_hora" datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "DF_a7551282e0c348adaf1f1421d82" DEFAULT getdate() FOR "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "moneda"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "moneda" nvarchar(5) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "estado" nvarchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP CONSTRAINT "UQ_cd029c805ebe7a9085206c25ac2"`);
        await queryRunner.query(`ALTER TABLE "mercado" DROP COLUMN "nombre"`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD "nombre" nvarchar(35) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mercado" ADD CONSTRAINT "UQ__mercado__72AFBCC6427EF4C9" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "DF_47f5efefb36304070dad826490f"`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "DF_47f5efefb36304070dad826490f" DEFAULT 0.00 FOR "consumo_diario"`);
        await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "DF_435d6261bd80a552fcc72cbd7ca"`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "DF_435d6261bd80a552fcc72cbd7ca" DEFAULT 0.00 FOR "saldo"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP CONSTRAINT "DF_37c5fbfba67129199a97366cce3"`);
        await queryRunner.query(`ALTER TABLE "recarga" DROP COLUMN "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD "fecha_hora" datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD CONSTRAINT "DF_37c5fbfba67129199a97366cce3" DEFAULT getdate() FOR "fecha_hora"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "UQ__usuarios__AB6E6164F0770675" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "UQ__usuarios__8C585C047AD715A0" UNIQUE ("alias")`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "DF_762fedc5a858bbb008722708ccd" DEFAULT newid() FOR "id_user"`);
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" ADD CONSTRAINT "DF_fda56775b3e828a758b3d3f7867" DEFAULT newid() FOR "id_phone"`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "UQ_User_Company" UNIQUE ("id_empresa", "id_user")`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "UQ_Company_PriceTimestamp" UNIQUE ("fecha_hora", "id_empresa")`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "CK__cartera_t__costo__7814D14C" CHECK (([costo_promedio]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "CK__cartera_t__canti__7720AD13" CHECK (([cantidad_acciones]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "CK__transacci__preci__7BE56230" CHECK (([precio]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "CK__transaccio__tipo__7AF13DF7" CHECK (([tipo]='Sell' OR [tipo]='Buy'))`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CK__empresa__estado__6501FCD8" CHECK (([estado]='Delisted' OR [estado]='Listed'))`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CK__empresa__accione__640DD89F" CHECK (([acciones_disponibles]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "CK__empresa__accione__6319B466" CHECK (([acciones_totales]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "CK__precio_hi__preci__68D28DBC" CHECK (([precio]>=(0)))`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "CK__wallet__categori__6E8B6712" CHECK (([categoria]='Senior' OR [categoria]='Mid' OR [categoria]='Junior'))`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD CONSTRAINT "CK__recarga__monto__725BF7F6" CHECK (([monto]>(0)))`);
        await queryRunner.query(`ALTER TABLE "auditoria" ADD CONSTRAINT "FK_Auditoria_User" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "FK_TP_Company" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cartera_trader" ADD CONSTRAINT "FK_TP_User" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "FK_Transaction_Company" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "transaccion" ADD CONSTRAINT "FK_Transaction_User" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "empresa" ADD CONSTRAINT "FK_Company_Market" FOREIGN KEY ("id_mercado") REFERENCES "mercado"("id_mercado") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "precio_historico" ADD CONSTRAINT "FK_PriceHistory_Company" FOREIGN KEY ("id_empresa") REFERENCES "empresa"("id_empresa") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "FK_Wallet_User" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "recarga" ADD CONSTRAINT "FK_TopUp_Wallet" FOREIGN KEY ("id_wallet") REFERENCES "wallet"("id_wallet") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_User_Role" FOREIGN KEY ("id_role") REFERENCES "roles"("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PhoneNumber_User" ADD CONSTRAINT "FK_PhoneNumber_User" FOREIGN KEY ("id_user") REFERENCES "usuarios"("id_user") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
